name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2:00 AM

jobs:
  test-php:
    name: Run PHP Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer, phpunit

      - name: Install Dependencies
        run: composer install

      - name: Run Tests
        run: composer test

  lint-shell:
    name: Lint Shell Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Shell Scripts with ShellCheck
        uses: ludeeus/action-shellcheck@v2

  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        run: |
          docker build -t your-dockerhub-username/nextcloud:latest .
          docker push your-dockerhub-username/nextcloud:latest

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Deploy Application
        run: |
          echo "Deploying application to production server..."
          # Add deployment commands here, e.g., SSH into your server and pull the latest Docker image.
